<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StreetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StreetRepository extends EntityRepository
{
    public function findStreetBySearchQuery($search_query)
    {
        $query = $this->createQueryBuilder('s')
            ->where('s.name LIKE :streetName')
            ->setParameter('streetName', "%{$search_query}%")
            ->orderBy('s.name', 'ASC')
            ->getQuery();

        return $query->getResult();
    }
}
